# Generated by Django 4.2.28 on 2026-04-13 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0004_add_created_on_to_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rareuser',
            name='active',
        ),
    ]
